Objetivo 0 - SportsBar [IV-22-23]
manujurado1/SportsBar-IV pull request #1
Opened 2022-09-26 16:48 UTC by manujurado1

* [X ] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [X ] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [X ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [X ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

2022-09-27 10:37 UTC, JJ requested changes
Por favor, revisa los problemas aceptables y la lógica de negocio que tienen que tener. Almacenar y buscar no está entre ellas. Tampoco parece que sea un problema real.

2022-09-27 10:37 UTC, JJ commented on README.md
> +El objetivo de esta plataforma es facilitar, en este caso, a los amantes del deporte residentes de Granada, encontrar el mejor bar dónde poder ver el partido que desea ver o simplemente el deporte de
Tienes que plantear un problema, no un producto.

2022-10-02 21:44 UTC, manujurado1 commented
Listo para revisión.

El nombre del repositorio ha dejado de tener sentido debido al cambio de propuesta.
@JJ

2022-10-03 10:41 UTC, JJ requested changes
* No tienes los datos para resolver el problema
* No está clara cuál es la lógica de negocio

2022-10-09 16:41 UTC, manujurado1 commented
Listo para revisión.
Se ha vuelto a cambiar la propuesta, buscando una parecida a la anterior pero esta vez teniendo a disposición los datos necesarios para resolver el problema y con una lógica de negocio más clara.
@JJ

2022-10-09 16:45 UTC, JJ requested changes
¿De qué forma "buscar la más barata" va más allá de buscar? Por favor, revisa el concepto de lógica de negocio y los diferentes ejemplos de lógicas de negocio aceptables o no que aparecen en el mismo.
De la misma forma, busca un problema real del que tengas conocimiento personal.

2022-10-10 08:06 UTC, manujurado1 commented
La idea es no limitarse a buscar la más barata, ya que si se trata de un viaje, quizás tienes que repostar antes de llegar a la que en números es la más barata. De ahí la idea de generar un reporte con las estadísticas, porcentajes y diferentes posibilidades, ya que no siempre la más barata es la mejor opción.
Y lo considero un problema de conocimiento personal debido a que siempre que tengo que repostar gasolina, intento informarme de en ese momento dónde me es más rentable repostar, y esta plataforma solucionaría este problema.

Si aún así esta propuesta no es válida,creo que no consigo entender como plantear una buena lógica de negocio.
@JJ

2022-10-10 08:10 UTC, manujurado1 commented
Quizás se puede añadir alguna opción de en función del alcance del vehículo, generar una lista de las gasolineras a las que puede ir a repostar y poder filtrar esa búsqueda por cercanía y/o precio con tal de añadir más contenido en la parte computacional

2022-10-10 12:27 UTC, JJ commented
> La idea es no limitarse a buscar la más barata, ya que si se trata de un viaje, quizás tienes que repostar antes de llegar a la que en números es la más barata. De ahí la idea de generar un reporte con las estadísticas, porcentajes y diferentes posibilidades, ya que no siempre la más barata es la mejor opción. Y lo considero un problema de conocimiento personal debido a que siempre que tengo que repostar gasolina, intento informarme de en ese momento dónde me es más rentable repostar, y esta plataforma solucionaría este problema.
> 

Para superar este objetivo es imprescindible:

1. Plantear bien el problema, y que sea un problema con el que se esté familiarizado y se tengan datos. En este caso, ni siquiera veo el problema (¿alguien se plantea la ruta en función de dónde tenga que repostar? Puedes plantearte si parar en la de al lado de casa o en medio de la carretera, pero no mucho más). 
2. Una vez planteado claramente el negocio, tienen que tenerse todos los datos necesarios para resolverlo. ¿Tienes las rutas? ¿De dónde piensas sacarlas? ¿El gasto de gasolina de cada ruta cómo lo calculas?

> Si aún así esta propuesta no es válida,creo que no consigo entender como plantear una buena lógica de negocio. @JJ

Pues conviene que entiendas como hacerlo, porque es imprescindible para superar este objetivo; es el objetivo, de hecho. En el guión de este objetivo viene diferentes ejemplos de qué constituye o no una lógica de negocio aceptable, así como diferentes fuentes de datos de donde puedes inspirarte para plantear problemas que las usen.

2022-10-10 14:34 UTC, manujurado1 commented
Se ha vuelto a cambiar la idea del proyecto.
Listo para revisión!
@JJ

2022-10-10 15:23 UTC, JJ approved these changes
Ni es un problema real (porque cuando se junta la gente a jugar o juega todo el mundo o se llevan la pelota) ni me parece que tengas claro que lo que planteas es bastante más complicado de lo que piensas, porque es un problema de optimización combinatoria relativamente complejo.
Tampoco es realista que un jugador tenga solo una puntuación, porque de hecho dependerá del equipo y de donde juegue.
Pero dicho eso, toca todos los palos que tiene que tocar para pasar el objetivo, así que adelante.

2022-10-10 15:45 UTC, manujurado1 commented
Quizás lo he planteado mal en el documento, el problema no reside en jugar o no jugar, ya que tiene razón en que o juegan todos o no se juega.
El problema que plantea resolver es que en cada sesión de juego se creen 2 equipos equilibrados para buscar una experiencia de juego óptima. 
Los equipos obviamente se crearían involucrando a todas las personas disponibles. A lo que yo me refería es que por ejemplo el total de gente que juega en ese grupo pueden ser 20, pero por sesión suelen ir 12, ya que no siempre todo el mundo puede.

Respecto a la optimización combinatoria, es verdad que es un tema bastante complejo pero en la plataforma no se buscaría la mejor combinación, sino una en la cuál la diferencia de nivel medio por equipo no sea muy grande.

Por último, respecto a lo de la única puntuación, en mi idea ahí entra el factor de interiormente ir modificando la puntuación en función de los resultados.  Viéndolo así, es cierto que una persona con menos nivel puede ganar un partido si su equipo es muy bueno, pero eso hará que su puntuación suba, lo que significa que al siguiente partido la puntuación media de sus compañeros será más baja debido a que la suya ahora es más alta (quizás no en el siguiente partido, pero sí si aumenta su puntuación desproporcionadamente por encima de su nivel real).
Por esta razón, con el paso de los partidos, los niveles de los jugadores acabaran rondando un umbral que reflejará su nivel real.

2022-10-10 15:58 UTC, JJ commented
> Quizás lo he planteado mal en el documento, el problema no reside en jugar o no jugar, ya que tiene razón en que o juegan todos o no se juega. El problema que plantea resolver es que en cada sesión de juego se creen 2 equipos equilibrados para buscar una experiencia de juego óptima. Los equipos obviamente se crearían involucrando a todas las personas disponibles. A lo que yo me refería es que por ejemplo el total de gente que juega en ese grupo pueden ser 20, pero por sesión suelen ir 12, ya que no siempre todo el mundo puede.
> 

Las cosas tienes que plantearlas de la mejor forma posible; si puedes corregirlo antes del siguiente, hazlo, por favor.

> Respecto a la optimización combinatoria, es verdad que es un tema bastante complejo pero en la plataforma no se buscaría la mejor combinación, sino una en la cuál la diferencia de nivel medio por equipo no sea muy grande.

Para eso tienes que plantear un algoritmo de optimización combinatoria.
> 
> Por último, respecto a lo de la única puntuación, en mi idea ahí entra el factor de interiormente ir modificando la puntuación en función de los resultados. Viéndolo así, es cierto que una persona con menos nivel puede ganar un partido si su equipo es muy bueno, pero eso hará que su puntuación suba, lo que significa que al siguiente partido la puntuación media de sus compañeros será más baja debido a que la suya ahora es más alta (quizás no en el siguiente partido, pero sí si aumenta su puntuación desproporcionadamente por encima de su nivel real). Por esta razón, con el paso de los partidos, los niveles de los jugadores acabaran rondando un umbral que reflejará su nivel real.

Con el tiempo todos tenderán a la media. Por eso te digo que el problema está muy cogido con pinzas, pero en fin, si lo planteas con precisión en el resto de los objetivos, a mi me vale.

2022-10-12 11:26 UTC, merged