Definición de nivel. #112
manujurado1/SportsBar-IV pull request #113
Opened 2023-06-01 18:28 UTC by manujurado1

Se ha definido el nivel como un entero cuyos valores pueden oscilar entre 1 y 10. closes #112

2023-06-05 12:54 UTC, JJ requested changes
Lo voy a admitir como PMV, pero tienes varios problemas:
1. Sigo pensando que la decisión de poner un tope es muy ad hoc y no está basada en un estudio de qué va a pasar con los equipos.
2. Establecer 10 niveles y no 3 o 30 también es una decisión arbitraria. 
3. Go tiene una forma específica de escribir las funciones y gestionar los errores. Aquí has optado por no gestionar el error, y "cortar" en los topes. Un linter te va a dar error en esas cosas, pero aunque no lo dé, no es una decisión adecuada.
4. No has tratado de ver cómo se va a usar la función. Lo más normal es que no se establezca el nivel más que al principio (y el valor por omisión deberías de establecerlo también como constante). El resto del tiempo se aumentará o se disminuirá el nivel. Como te dije, la implementación es mejor ocultarla. Aquí el usuario necesita saber explícitamente que los niveles son enteros y cosas así.
5. Poner el nivel mínimo en 1 es arbitrario, pero lleva a que sea imposible poner un nivel inicial que esté justo en la mitad. De 5 a 10 hay 5 niveles, de 5 a 1 sólo 4.

En fin, ya te digo que nada es fácil, y debes realmente examinar el problema y tratar de encontrar soluciones adecuadas, que sigan una serie de parámetros. Esta... es una solución, podría ser válida como PMV, pero nada más.

En todo caso, el principal obstáculo es que no puedes resolver ningún issue sin tests, este no lo tiene. Es imprescindible en desarrollo ágil asegurar mediante tests que el comportamiento de la estructura de datos es el adecuado.

2023-06-05 13:15 UTC, manujurado1 commented
Vale, entendido. Cuando acabe de trabajar corrijo los puntos que me indicas.

Lo único que no termino de entender es lo siguiente:

> 2. Establecer 10 niveles y no 3 o 30 también es una decisión arbitraria.

En este apartado, según hemos hablado en otras ocasiones, cualquier decisión es correcta siempre que esté argumentado. Por lo que mi pregunta es: ¿Qué forma es la idónea para justificar la elección de un rango de niveles u otro?

Muchas gracias por la corrección @JJ

2023-06-05 15:13 UTC, JJ commented
> Vale, entendido. Cuando acabe de trabajar corrijo los puntos que me indicas.
> 
> Lo único que no termino de entender es lo siguiente:
> 
> > 2. Establecer 10 niveles y no 3 o 30 también es una decisión arbitraria.
> 
> En este apartado, según hemos hablado en otras ocasiones, cualquier decisión es correcta siempre que esté argumentado. Por lo que mi pregunta es: ¿Qué forma es la idónea para justificar la elección de un rango de niveles u otro?
> 

La mínima que resuelva el problema, que tiene que estar bien planteado. Si haces TDD, la primera que pase los tests.

2023-06-07 07:05 UTC, JJ requested changes
En general, no debes crear diferentes funciones que hagan lo mismo: tienes que hacer un interfaz mínimo. Si tienes funciones para aumentar y disminuir nivel, que son las únicas además que vas a usar, *no debes* tener una adicional para establecer el nivel.
Por otro lado, estás tomando también una decisión implícita aquí: pasar el Nivel por valor, y lo devuelves modificado. En Go los puedes pasar por valor o por referencia. Cuando tomes estas decisiones (que pueden parecer nimias), debes *siempre* consultar las mejores prácticas. Parece ser que en este caso es así https://www.reddit.com/r/golang/comments/wl7qyx/when_writing_functions_when_should_i_pass_by/ pero es conveniente que lo hagas.
Adicionalmente, en las dos funciones haces una operación + una decisión siempre. En muchos casos. puedes resolverlo con sólo una decisión. Además, estás decidiendo que se aumente el nivel una cantidad determinada, cuando el producto mínimamente viable sólo pide que se aumente, sin especificar la cantidad; eso fuerza también a que la persona que usa la clase tenga que declarar un nivel para pasar al nivel... En fin, lo complica todo un poco. Recuerda que las primeras versiones de todo lo que hagas tienen que ser
1. Simples
2. Adaptables (por el open/closed principle)

2023-06-07 07:21 UTC, manujurado1 commented
Gracias por la corrección @JJ 
Respecto a lo que comentas del interfaz mínimo, yo si considero necesario una función (en este caso usada como constructor) para insertar el nivel. Ya que cuando haya que crear un Amigo, será necesario indicar el nivel del mismo (debido a que no tienen todos los amigos que crearse con el mismo nivel inicial). Y ahí será necesario usar el constructor del objeto valor nivel para comprobar que el dato introducido es correcto y en ese caso crear el objeto Nivel.

Respecto al paso por referencia o valor, no fue ese artículo pero si estuve mirando y por eso en el ultimo commit lo cambié y dejé de trabajar con referencias debido a que no iba a mutar el objeto, sino que iba a destruirlo y crear uno nuevo cuando este se modificara.

Por último, respecto al tema de aumentar y disminuir nivel, concuerdo con lo que dices, lo cambiaré en cuanto pueda.

2023-06-07 08:31 UTC, manujurado1 commented
> Los constructores en Go siguen una convención específica, creo recordar que era el mismo nombre del struct. Y como tú mismo has dicho, se construye con un nivel por omisión, no con cualquier nivel. Las decisiones que tomes sobre los tipos y que salgan del domain driven design debes incluirlas en el diseño del tipo. Por supuesto, en vez de comprobar (o no) que el nivel es correcto, lo mejor siempre es forzar a que se creen siempre con un nivel correcto, el nivel por omisión.

Relamente en Go no hay constructores como tal, pero se usan funciones para replicar el funcionamiento de los constructores. En este caso, lo llamé NuevoNivel para seguir el lenguaje oblícuo.
Y respecto a lo que comentas del nivel por omisión, el nivel inicial de cada jugador no debe ser por omisión, tiene que ser decisión del usuario decidir el nivel con el que se crea cada amigo. Por esa razón está el constructor que comprueba si el nivel introducido es válido, y sino da error y devuelve el nivel por omisión.

2023-06-07 09:42 UTC, JJ commented
> > Los constructores en Go siguen una convención específica, creo recordar que era el mismo nombre del struct. Y como tú mismo has dicho, se construye con un nivel por omisión, no con cualquier nivel. Las decisiones que tomes sobre los tipos y que salgan del domain driven design debes incluirlas en el diseño del tipo. Por supuesto, en vez de comprobar (o no) que el nivel es correcto, lo mejor siempre es forzar a que se creen siempre con un nivel correcto, el nivel por omisión.
> 
> Relamente en Go no hay constructores como tal, pero se usan funciones para replicar el funcionamiento de los constructores. En este caso, lo llamé NuevoNivel para seguir el lenguaje oblícuo. Y respecto a lo que comentas del nivel 

No sé qué es el lenguaje oblicuo; pero por lo que veo, la mejor práctica es usar New+nombre del tipo, en inglés https://github.com/manujurado1/SportsBar-IV/pull/113#issuecomment-1580083583

> por omisión, el nivel inicial de cada jugador no debe ser por omisión, tiene que ser decisión del usuario decidir el nivel con el que se crea cada amigo. Por esa razón está el constructor que comprueba si el nivel introducido es válido, y sino da error y devuelve el nivel por omisión.

Una vez más, tienes que buscar el producto mínimamente viable y meter decisiones de diseño en el código. Por lo pronto, ni siquiera tienes una historia de usuario de "persona que mete a amigos". Tampoco tienes una historia de usuario que diga que el usuario conoce como juegan sus amigos y es capaz de asignarle un nivel. Pero lo más importante aquí es que debes separar el interfaz de la implementación, encapsulando el "estado" que tú hayas decidido para esa variable. Si no lo encapsulas, entonces el usuario tiene que saber cómo has diseñado los niveles, que son enteros, que les has puesto un tope y demás. Si simplemente lo creas con un usuario por defecto el usuario, como tiene que ser, no necesita ningún conocimiento de la implementación para crear un usuario.

Separar el interfaz de la implementación es fundamental, porque forma práctica de lo que se llama "programación defensiva": crear aplicaciones sin deuda técnica (sin decisiones tomadas apresuradamente que cuesta mucho trabajo cambiar) y que sean fácilmente adaptables en caso de decidir cambiar de implementación (pasar de 10 a 3 niveles, de niveles con tope a niveles sin tope). Mira el open/closed principle, por ejemplo.

En todo caso, siempre que justifiques una decisión con "he pensado que" piensa que está mal. La única justificación de una decisión es 
1. Aporta valor al cliente, cumpliendo una historia de usuario
2. Necesita un mínimo de trabajo para hacerlo

Si sigue suposiciones implícitas que no están documentadas o que pueden impedir que algo se haga bien en el futuro, o no siguen las mejores prácticas, no es una buena justificación.

2023-06-07 11:57 UTC, manujurado1 commented
@JJ Ya creo que está el código adaptado a todo lo discutido.

2023-06-07 17:56 UTC, merged

2023-06-08 12:32 UTC, JJ commented
> > Vamos a no darle más vueltas, pero por favor ten en cuenta una serie de cosas
> > 
> > 1. Estás usando un alias en vez de un struct, lo que puede ser un problema a la hora de evolucionarlo. Con un alias puedes asignarle valor directamente (como haces en el test), con un struct también, pero no si no sabes qué se usa para representarlo. Más si usas alguna convención (como en Python) del tipo poner un `_` delante para que sea "oculto" (no sé si habrá alguna forma efectiva de hacerlo oculto en Go, es posible).
> 
> Respecto a o que comentas de que no sea un struct, planteé la opción de que lo fuera, pero como tendría solo un atributo y vi la opción del alias me convenció más esta. Por otra parte, la convención de ocultamiento es la misma en Go que en Python, ya que si en vez de la _ pongo otro nombre salta el linter diciendo que no se ha usado.

Un struct te habría dado más juego; por ejemplo, poder impedir en la construcción que sobrepase los topes. Piensa en todo caso que structs, u objetos en general, son siempre más convenientes si quieres separar interfaz de implementación (que siempre es bueno) encapsulando los datos.
> 
> > 2. En los tests debes comprobar comportamiento, básicamente que si lo subes el nuevo nivel va a ser mayor o igual, y que si lo bajas menor o igual (por el tope, que una vez más, no me gusta, pero si no fuera por el tope no haría falta). Los tests que estás haciendo no comprueban comportamientos, sino que están una vez más comprobando la implementación y violando la encapsulación. En ese sentido, no tienes que comprobar si se ha alcanzado el nivel mínimo o el máximo, _porque no hay ninguna HU que diga que tiene que ser así_. Los tests comprueban las HUs y punto.
> 
> El tema de los tests si que lo veo un error, ya que un cambio en la implementación (como que la modificación de niveles sea de mayor o menor cantidad, haría que no pasaran los tests cuando realmente si deberían pasar ya que si cumplirían la HU.

Efectivamente. Siempre hay que escribir los tests pensando en posibles cambios de implementación en el futuro.
> 
> > En todo caso, felicitaciones por la paciencia y por intentarlo hasta que se ha conseguido.
> 
> Gracias y te agradezco la paciencia también ya que quizás estoy fallando en cosas que si debería saber.

No estás fallando en nada, estás aprendiendo, que es para lo que está un TFG.