M3 - Gestión niveles post-partido. #126
manujurado1/SportsBar-IV pull request #127
Opened 2023-06-20 18:26 UTC by manujurado1

En primer lugar se han cambiado las funciones de aumentar y decrementar nivel ya que estas solo se usan tras un partido y se aplican en conjunto a un equipo. Como no es algo ligado al comportamiento del usuario, se han eliminado los tests. Estas funciones se testean ahora dentro del test de modificar niveles post partido. Se ha establecido como criterio de modificación que se aumenta el nivel si se gana y se disminuye si se pierde, independientemente de lo abultado que sea el resultado. Si el partido queda en empate, todo queda igual. closes #126

2023-06-20 18:28 UTC, manujurado1 commented
Ya estaría listo para revisión! @JJ 
Una vez aprobado esto se daría por terminado el milestone actual, el cual contiene la inclusión de la lógica de negocio.

2023-06-21 08:21 UTC, JJ requested changes
El principal problema es cómo se crean los equipos sin todos los datos adecuados. Pero el tema de los errores también deberías considerarlo, si tienes tiempo.

2023-06-21 08:21 UTC, JJ commented on pkg/modelos/grupo.go
> +	ErrorEquiposPartidoDistinto                      = fmt.Errorf("Los equipos introducidos no son del mismo partido ya que tienen fechas diferentes")
Sigo diciéndote lo mismo: si no dices qué equipos has introducido, es imposible recuperarse de ese error. Los errores están hecho para poder mirar un mensaje de error entre mensajes de depuración y saber qué es lo que lo ha causado. Por eso es esencial proporcionar todos los datos necesarios para poder averiguarlo.

2023-06-21 08:21 UTC, JJ commented on pkg/modelos/grupo_test.go
> +	equipo1.fechaCreacion = time.Date(2023, time.June, 19, 0, 0, 0, 0, time.Now().Location())
No crear un equipo con una fecha de corrección correcta puede ser un error.

2023-06-21 08:27 UTC, manujurado1 commented on pkg/modelos/grupo.go
> +	ErrorEquiposPartidoDistinto                      = fmt.Errorf("Los equipos introducidos no son del mismo partido ya que tienen fechas diferentes")
Vale, me pondré hoy a revisar todos los casos de error y crear funciones para hacerlos dinámicos y que devuelvan la información más detallada posible.

2023-06-21 08:30 UTC, manujurado1 commented on pkg/modelos/grupo_test.go
> +	equipo1.fechaCreacion = time.Date(2023, time.June, 19, 0, 0, 0, 0, time.Now().Location())
El atributo fecha de creación de un equipo se crea automáticamente cuando se crea el Equipo con la fecha actual en ese momento, por lo que nunca se va a crear con una fecha incorrecta. En este caso, estoy sobreescribiendo la fecha con una fecha distinta a la actual para comprobar el caso de error de introducir el resultado con 2 equipos con fechas diferentes.

2023-06-21 09:20 UTC, JJ commented on pkg/modelos/grupo_test.go
> +	equipo1.fechaCreacion = time.Date(2023, time.June, 19, 0, 0, 0, 0, time.Now().Location())
¿No hay ninguna forma de evitar que se sobreescriban ciertas variables de instancia? Como siempre, forzar que algo suceda usando los mecanismos del lenguaje es mucho mejor que hacer comprobaciones en tiempo de compilación

2023-06-21 09:25 UTC, JJ commented on pkg/modelos/grupo_test.go
> +	equipo1.fechaCreacion = time.Date(2023, time.June, 19, 0, 0, 0, 0, time.Now().Location())
Estoy viendo que no hay variables privadas en structs; dice que la mejor práctica es simplemente evitar hacerlo; en todo caso crear un error y testear para algo que es complicado hacer o no tiene sentido porque no está expuesto al público no sé si añade mucho valor. Y ahora que lo pienso, identificar partidos solo por fecha obliga a que haya un partido sólo al día; sería conveniente que especificaras eso en las historias de usuario.

2023-06-21 09:25 UTC, JJ approved these changes
Si se crean los equipos con los datos adecuados no se bloquea la fusión del PR, es simplemente una cuestión a refactorizar o no testear.

2023-06-22 08:26 UTC, JJ commented
> Vale, entonces entiendo que lo que tengo que hacer es quitar la parte del test que compruebo esa salida de error verdad? Y si es así y no lo testeo, ¿es necesario que haga esa comprobación y por consiguiente, que exista el atributo fecha en un equipo?

En las revisiones nunca se puede decir qué es lo que uno quiere que se haga. Simplemente haz lo que estimes conveniente, y se acepta o no. En todo caso ya está aceptado, como ves, el que lo cambies o no, antes de fusionar o más adelante, es cosa tuya.

2023-06-22 16:53 UTC, merged