M4 Elección framework REST API. #128
manujurado1/SportsBar-IV pull request #129
Opened 2023-06-22 17:41 UTC by manujurado1

Se ha elegido usar Gin como framework para crear la API REST debido a las facilidades que aporta frente a la biblioteca estandar y por su gran comunidad, la cuál ofrece más tutoriales y soluciones que los otros frameworks mencionados. closes #128 

![image](https://github.com/manujurado1/SportsBar-IV/assets/74008375/2dcf46c8-9f5a-4651-9467-e0ec19642844)
![image](https://github.com/manujurado1/SportsBar-IV/assets/74008375/608c330a-bf94-4601-88b5-9849b9b4b576)

2023-06-23 08:15 UTC, JJ requested changes
Esto no es un objetivo de IV, y ni siquiera ahí funcionaba lo de "facilidad de uso" y demás. Por favor, trata de poner las razones reales por la que lo has elegido y qué requisitos tenías. ¿Qué necesitabas de él, aparte de ser ligero? ¿Debía de manejar rutas de forma independiente? ¿Ser fácil para añadir middleware? ¿Tener el sistema de logs de Go integrado?

2023-06-23 08:15 UTC, JJ commented on docs/secciones/06_implementacion.tex
> +  Facilidad de uso.
No es un criterio objetivo

2023-06-23 08:16 UTC, JJ commented
Adicionalmente, debes meter el código donde realmente lo empieces a usar en el mismo PR, o hacerlo antes, en todo caso.

2023-06-23 08:30 UTC, manujurado1 commented
> Adicionalmente, debes meter el código donde realmente lo empieces a usar en el mismo PR, o hacerlo antes, en todo caso.

Entendido, había pensado en entregar solo la elección en un PR para asegurar que el framework elegido era apto antes de empezar a trabajar con él.

2023-06-23 08:55 UTC, JJ commented
> > Adicionalmente, debes meter el código donde realmente lo empieces a usar en el mismo PR, o hacerlo antes, en todo caso.
> 
> Entendido, había pensado en entregar solo la elección en un PR para asegurar que el framework elegido era apto antes de empezar a trabajar con él.

No sé si te das cuenta que realmente antes de empezar a trabajar con él es casi imposible saber si es apto o no... Del manual poco puedes sacar para comparar.

2023-06-23 08:56 UTC, manujurado1 commented
> > > Adicionalmente, debes meter el código donde realmente lo empieces a usar en el mismo PR, o hacerlo antes, en todo caso.
> > 
> > 
> > Entendido, había pensado en entregar solo la elección en un PR para asegurar que el framework elegido era apto antes de empezar a trabajar con él.
> 
> No sé si te das cuenta que realmente antes de empezar a trabajar con él es casi imposible saber si es apto o no... Del manual poco puedes sacar para comparar.

Si, tienes razón, puedo sacar un estudio según manual y eso, pero si a la hora de la verdad no hace lo que necesito sirve de poco.

2023-06-26 08:00 UTC, manujurado1 commented
No entiendo por qué ahora el linter no encuentra los .go 😞

2023-06-26 08:21 UTC, JJ commented
¿Está bien configurado con la configuración por omisión? ¿No tendrás que meterle un YAML para eso?

2023-06-26 08:22 UTC, JJ requested changes
Para implementar el API y testearlo no necesitas la función main. Limita este PR al API en sí.

2023-06-26 08:27 UTC, manujurado1 commented
> ¿Está bien configurado con la configuración por omisión? ¿No tendrás que meterle un YAML para eso?

Se supone que no, directamente busca los ficheros go en el repositorio y los analiza. Cuando hago el golangci-lint run desde mi terminal no me falla, no sé puede ser por un problema de versiones del linter.

2023-06-26 22:38 UTC, manujurado1 commented
Creo que el fallo da porque el action no tiene instalado el framework Gin y por eso peta. Mañana seguiré investigando. De todas formas el linter me pasa sin fallos en local

2023-06-28 08:05 UTC, manujurado1 commented
Al fin! Perdón por el spam @JJ Ya está listo para revisión

2023-06-29 15:18 UTC, JJ requested changes
Los criterios no son demasiado objetivos, y tampoco son comparables las herramientas. http ni siquiera es un microframework o framework para microservicios.

2023-06-29 15:31 UTC, manujurado1 commented on .github/workflows/golangci-lint.yml
> +          version: v1.51.0
Me sale este comentario como que es de ayer pero me acaba de llegar ahora...
Al final se solucionó cambiando la versión de Go en el action, creo que la version del lint puedo volver a poner latest

2023-06-29 15:31 UTC, JJ commented
> > Los criterios no son demasiado objetivos, y tampoco son comparables las herramientas. http ni siquiera es un microframework o framework para microservicios.
> 
> Ya, pero una de las opciones era no usar frameworks y usar la librería estandar, que es http/net, por eso la incluí.

Son decisiones diferentes, entonces. 1ª Uso microframeworks o minimizo dependencias 2ª Si microframeworks, cual. En general, no debes comparar cosas que no son comparables.

2023-06-29 15:32 UTC, manujurado1 commented on docs/secciones/06_implementacion.tex
> +  Este framework también se caracteriza por ser ligero y enfocarse en el rendimiento de la aplicación.
Consideras que es un criterio poco importantes? Sería mejor centrarse en las facilidades que te ofrezca sin tener tanto en cuenta como pueda afectar al rendimiento?

2023-06-29 15:33 UTC, JJ commented on .github/workflows/golangci-lint.yml
> +          version: v1.51.0
Si, se me olvidó darle al "finish review". En general, usar versiones fijas significa que vas a tener que cambiarlo tarde o temprano... El error que había, de todas formas, no parecía tener nada que ver con las versiones.

2023-06-29 15:35 UTC, JJ commented on docs/secciones/06_implementacion.tex
> +  Este framework también se caracteriza por ser ligero y enfocarse en el rendimiento de la aplicación.
No he dicho eso, digo que no es objetivo, no puedes decir este es más ligero que aquél en un 20%. En general, todos los microframeworks van a ser más o menos "ligeros", por eso se llaman "micro". Más allá están frameworks MVC o por el estilo. Por eso tienes que definirlo claramente.
Y como en IV, decir por qué eso es importante para tu proyecto o no.

2023-06-29 16:01 UTC, manujurado1 commented on docs/secciones/06_implementacion.tex
> +  Este framework también se caracteriza por ser ligero y enfocarse en el rendimiento de la aplicación.
Vale, entiendo, lo modifico!

2023-06-29 16:53 UTC, manujurado1 commented
Ya le he dado una vuelta a todo! @JJ

2023-06-29 18:08 UTC, JJ approved these changes
No voy a darle más vueltas, pero de verdad que lo de la "comunidad activa" no funcionaba en IV, aquí tampoco va a funcionar. Si quieres hacerlo medio en serio usa Snyk, que creo que hay también para Go.

2023-06-30 18:14 UTC, manujurado1 commented
> No voy a darle más vueltas, pero de verdad que lo de la "comunidad activa" no funcionaba en IV, aquí tampoco va a funcionar. Si quieres hacerlo medio en serio usa Snyk, que creo que hay también para Go.

Ok, lo cambio por la puntuacion del GoReportCard antes de mergearlo, que es el símil de Snyk en Go

2023-06-30 18:40 UTC, merged