[IV-22-23] Objetivo 2
manujurado1/SportsBar-IV pull request #17
Opened 2022-11-27 01:50 UTC by PabloSpiegel

Sobre la estructura del repositorio

* [x] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
   disposición de los mismos?

Sobre el análisis del problema

* [x] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [x] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [x] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

Sobre la planificación y la programación

* [x] ¿Los issues representan un problema, y no una tarea?
* [x] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [x] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [x] ¿Todos los issues creados están asignados a una HU?
* [x] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit? Los issues sobre los que estoy trabajando, ¿han
      sido asignados al primer milestone?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [x] ¿Son los milestones sobre los que estoy trabajando productos
   mínimamente viables? ¿O tengo que solicitar al product manager que
   cree milestones adicionales o precise de qué producto se trata?
* [x] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

2022-11-27 01:53 UTC, PabloSpiegel commented
Hola @manujurado1. Cuando mires esto asigna este PR al M0, para así poder tachar el último tick que queda.

Si quieres comentar cualquier cosa que harías distinta con una review aquí estoy :)

2022-11-28 13:05 UTC, manujurado1 commented
Buenas Pablo, tras revisarlo, he visto que las clases están dentro de la carpeta /pkg, pero según he visto en las prácticas recomendadas, pienso que /internal sería su directorio adecuado. Te dejo aquí el link del cual he sacado la información:
https://blog.friendsofgo.tech/posts/como_estructurar_tus_aplicaciones_go/

2022-11-28 13:57 UTC, PabloSpiegel commented
ya he añadido el check que faltaba. Yo es que he pensado que no hay ningún archivo que vaya a hacer un procesamiento interno, que todo se podría usar para otro programa.

2022-11-28 19:07 UTC, manujurado1 commented
Vale, creo que ambos enfoques son válidos. También he revisado el código y está todo tal y como hemos ido discutiendo.
Te apruebo los cambios. 
Muy buen trabajo!

2022-11-28 19:10 UTC, manujurado1 approved these changes

2022-11-28 19:47 UTC, PabloSpiegel commented
@JJ listo para revisión

2022-11-30 11:20 UTC, JJ commented
Es más fácil para quien corrige que el issue con el que se trabaja esté en la primera línea del commit.

2022-11-30 11:21 UTC, JJ commented
> Buenas Pablo, tras revisarlo, he visto que las clases están dentro de la carpeta /pkg, pero según he visto en las prácticas recomendadas, pienso que /internal sería su directorio adecuado. Te dejo aquí el link del cual he sacado la información: https://blog.friendsofgo.tech/posts/como_estructurar_tus_aplicaciones_go/

Cualquiera de los dos es correcto. Lo importante, en todo caso, es que lo hayáis consultado.

2022-11-30 11:33 UTC, JJ requested changes
No acabo de ver cómo encajan unos componentes con otros, por lo tanto el "modelo" no está nada claro, pero el problema principal es que tienes que tener claro qué issues estás desarrollando y en qué milestones están.

2022-11-30 11:33 UTC, JJ commented on pkg/jugador.go
> +type Jugador struct{
El trabajar con domain driven design fuerza a pensar cómo se va a trabajar con una estructura de datos determinada desde el punto de vista de la lógica de negocio. En ese sentido, si el objeto más simple en el que puedas pensar (como este) no es inmutable, es que va a haber algún problema y no has modelizado bien el problema.

2022-11-30 11:33 UTC, JJ commented on pkg/jugador.go
> +  Disp bool
Como te he dicho en #14, no hay nada en la historia de usuario que diga esto.
En todo caso, el nombre debe ser lo más informativo posible.

2022-11-30 11:33 UTC, JJ commented on pkg/partido.go
> +type Partido struct{
De #3 no se deduce que haya que tener un Partido como estructura de datos de partida para aplicar la lógica de negocio. Más bien parece que haya que tener un resultado. #4 no está en este milestone.

2022-12-01 08:49 UTC, PabloSpiegel commented
@JJ Listo para otra revisión.

Gracias por los apuntes. He dejado de lado #15 y he quitado la clase jugador para simplificar el modelo

2022-12-01 09:06 UTC, PabloSpiegel commented
@JJ Listo para otra revisión con los cambios que hacían falta.
Cada HU es para un grupo de gente distinto y de ahí entiendo que sale la necesidad de que haya distintos grupos, y que cada uno tenga nombre

2022-12-01 09:19 UTC, JJ approved these changes
Voy a optar por aprobar, aunque en algún lugar tendría que estar *todos* los jugadores que pueden estar disponibles.

2022-12-02 13:00 UTC, merged