[IV-22-23] Objetivo 3
manujurado1/SportsBar-IV pull request #21
Opened 2022-12-27 12:00 UTC by manujurado1

* [x] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [x] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [x] ¿Ese issue está asignado a un milestone?
* [x] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [x] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [x] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [x] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2022-12-28 10:51 UTC, JJ commented
Los milestones son herramientas efectivas de desarrollo, que ayudan a la persona que desarrolla a saber qué tiene que desarrollar en cada momento y en qué orden hacerlo. No son "cosas que hay que poner en esta asignatura para superar el objetivo". No se trata de que enlacéis un milestone. Ya imagino que sabéis crear un enlace desde un formulario. Se trata de que el enunciado de ese milestone, efectivamente, incluya el producto que resulte de fusionar este código.
Por otro lado, te agradecería que siguieras una vez más las buenas prácticas en mensajes de commit. No hay ni uno de los enlazados que las siga: ninguno enlaza un issue en la primera línea. Te recuerdo, en todo caso, que *todo* código tiene que desarrollarse siguiendo un issue.

2022-12-29 09:38 UTC, manujurado1 commented
> Los milestones son herramientas efectivas de desarrollo, que ayudan a la persona que desarrolla a saber qué tiene que desarrollar en cada momento y en qué orden hacerlo. No son "cosas que hay que poner en esta asignatura para superar el objetivo". No se trata de que enlacéis un milestone. Ya imagino que sabéis crear un enlace desde un formulario. Se trata de que el enunciado de ese milestone, efectivamente, incluya el producto que resulte de fusionar este código. Por otro lado, te agradecería que siguieras una vez más las buenas prácticas en mensajes de commit. No hay ni uno de los enlazados que las siga: ninguno enlaza un issue en la primera línea. Te recuerdo, en todo caso, que _todo_ código tiene que desarrollarse siguiendo un issue.

Ya he editado el M0 para que este PR y los issues que resuelve tengan sentido dentro de ese propio milestone.
Respecto a los commits, tendré en cuenta las mejores prácticas que hablamos ayer en el objetivo 2. 
En este caso todos los commits referencian un issue (aunque no en la primera línea, que lo haré así de aquí en adelante) excepto el último, que arregla un fallo de sintaxis que se arrastraba desde el objetivo 2 que descubrí cuando comprobé la funcionalidad de la orden check, pero no sé si ese fix debería haberlo hecho fuera de este PR.

Por lo que una vez solucionado lo del milestone está listo para revisión y en caso que sea necesario eliminaré la correción del error de sintaxis y lo arreglaré fuera de este PR.

Muchas gracias! @JJ

2022-12-29 16:30 UTC, manujurado1 commented
Buenas @JJ le etiqueto de nuevo ya que me sale que ha reaccionado a mi mensaje de solicitar revisión pero no ha habido ningún comentario al respecto por si hubiera sido un fallo o algo del estilo.
Si no ha sido así, pues perdon por la molestia.

2022-12-29 16:45 UTC, JJ commented
No, ninguno. Simplemente no lo he hecho. De todas formas, revisa errores frecuentes, como es habitual y mira a ver si alguna cosa no estuviera bien.

2022-12-30 10:10 UTC, manujurado1 commented
@JJ He estado revisando todo lo entregado y me ha surgido una duda, considero que el último commit que arregla la sintaxis no debe ir en este PR ya que no es evaluable, pero no tengo claro cuál es el mejor método para hacerlo. A mi se me ocurre crear otra rama para arreglar el error de sintaxis, mergearlo a la rama main y luego rebasear esta rama con main, ¿debería hacerlo así?
Por lo demás considero que el objetivo está listo para ser revisado (a excepción del fallo en los mensajes de commit que los haré de forma correcta de aquí en adelante).
Muchas gracias!

2022-12-30 10:27 UTC, JJ commented
> @JJ He estado revisando todo lo entregado y me ha surgido una duda, considero que el último commit que arregla la sintaxis no debe ir en este PR ya que no es evaluable, pero no tengo claro cuál es el mejor método para hacerlo. A mi se me ocurre crear otra rama para arreglar el error de sintaxis, mergearlo a la rama main y luego rebasear esta rama con main, ¿debería hacerlo así? Por lo demás considero que el objetivo está listo para ser revisado (a excepción del fallo en los mensajes de commit que los haré de forma correcta de aquí en adelante). Muchas gracias!

También está explicado en errores frecuentes, creo que hace 3 o 4 semanas. Se hace un PR aparte a main y luego se mergea desde main a esta rama.

2022-12-30 10:57 UTC, manujurado1 commented
> También está explicado en errores frecuentes, creo que hace 3 o 4 semanas. Se hace un PR aparte a main y luego se mergea desde main a esta rama.

Arreglado, gracias! 👍 
Pues ahora está todo listo a mi parecer.

2023-01-03 11:14 UTC, JJ requested changes
Sería conveniente que hiciérais un poco de esfuerzo para siquiera tratar de aplicar los criterios que vosotros mismos habéis puesto a las herramientas elegidas. En todo caso, lo conveniente sería que *realmente* tratárais de aplicar esos criterios, después de elegir unos criterios razonables y objetivos.
Consulta en todo caso los errores frecuentes en este objetivo.

2023-01-03 11:14 UTC, JJ commented on docs/Gestor_Tareas.md
> +Tras hacer una búsqueda de las posibles opciones se han llegado a 2 posibles candidatos a ser el gestor de tareas del proyecto.
¿Cuales han sido los resultados de esta búsqueda?

2023-01-03 11:14 UTC, JJ commented on docs/Gestor_Tareas.md
> +- Comunidad activa
¿Cómo mides esto de forma objetiva?

2023-01-03 11:14 UTC, JJ commented on docs/Gestor_Tareas.md
> +- Compatibilidad con el lenguaje (Go)
¿Qué significa "compatibilidad" con el lenguaje? En todo caso, si no es "compatible" ni siquiera lo podrás usar y por tanto será un requisito y no un criterio, ¿no?

2023-01-03 11:14 UTC, JJ commented on docs/Gestor_Tareas.md
> +- Su instalación no es complicada
¿Qué criterio es este?

2023-01-03 11:14 UTC, JJ commented on docs/Gestor_Tareas.md
> +- Debido a facilidad de uso y complejidad de sintaxis, he elegido que Task será el gestor de tareas elegido para este proyecto.
¿Qué freshness tiene?

2023-01-03 11:45 UTC, manujurado1 commented on docs/Gestor_Tareas.md
> +- Compatibilidad con el lenguaje (Go)
Si, tienes razón, mi idea al añadir este criterio es elegir un gestor de tareas que esté ya listo para usar con Go y no tuviera que usarse de una forma "antinatural" para que sirva con Go. Pero si es verdad que cambiar el criterio y usar el termino de mejores prácticas creo que refleja mejor el criterio

2023-01-03 11:47 UTC, manujurado1 commented on docs/Gestor_Tareas.md
> +- Comunidad activa
Con este requisito no busco usar el task manager con la comunidad más activa, sino un check que debe cumplir el task manager para ser viable en este proyecto. Si es cierto que para lo que para mi puede ser una comunidad activa para otra persona quizás no lo sea. Por lo que contemplaré o eliminar el criterio o cambiarlo por otro con una medición más objetiva que apunte a las mismas características.

2023-01-03 11:48 UTC, JJ commented on docs/Gestor_Tareas.md
> +- Compatibilidad con el lenguaje (Go)
Go es un lenguaje compilado, que usa subcomandos de `go` para realizar casi todas sus actividades. Difícil que algo *no* sea compatible con eso, es decir, que sea incapaz de lanzar comandos del shell.

2023-01-03 11:51 UTC, manujurado1 commented on docs/Gestor_Tareas.md
> +Tras hacer una búsqueda de las posibles opciones se han llegado a 2 posibles candidatos a ser el gestor de tareas del proyecto.
Pues la búsqueda ha constado desde el minuto 0 buscar que es un task manager y van apareciendo diferentes gestores, pero una vez enfocado en Go, son estos 2 los que tomaban más relevancia, por eso paso directamente a estas 2 opciones.
Pero si esta no es una buena forma de plasmarlo, lo cambiaré por algo más descriptivo que explique mejor el proceso, pero en su momento lo obvié ya que lo consideraba información extra que no tenía importancia.

2023-01-03 11:53 UTC, manujurado1 commented on docs/Gestor_Tareas.md
> +- Su instalación no es complicada
Cierto, al final usé la instalación como un criterio para la elección del gestor pero no lo añadí arriba en los criterios. Lo corrijo 👍

2023-01-03 11:57 UTC, JJ commented on docs/Gestor_Tareas.md
> +Tras hacer una búsqueda de las posibles opciones se han llegado a 2 posibles candidatos a ser el gestor de tareas del proyecto.
No te estoy diciendo eso. Te estoy diciendo que pongas los resultados de la búsqueda, que es explícitamente lo que se pide en el objetivo. Los que cumplan los requisitos, al menos.

2023-01-03 11:59 UTC, manujurado1 commented on docs/Gestor_Tareas.md
> +- Debido a facilidad de uso y complejidad de sintaxis, he elegido que Task será el gestor de tareas elegido para este proyecto.
No entiendo si esta pregunta se refiere a que en la elección tengo que volver a nombrar los criterios por así decirlo para demostrar que los cumple, que tiene todo el sentido del mundo y si es así lo añadiré.
O la pregunta es porque no considera que Taskfile no es una herramienta con una buena freshness. Que si es así, yo lo consideré apto debido a que vi en la pagina oficial las diferentes versiones que han ido saliendo y como han ido ampliando su funcionalidad y luego en el github de la herramienta tenía aportaciones recientes, por lo que la consideré con un freshness adecuado

2023-01-03 12:03 UTC, manujurado1 commented on docs/Gestor_Tareas.md
> +- Compatibilidad con el lenguaje (Go)
Si, cuando puse los criterios aún no conocía la facilidad para este tipo de cosas que tiene go, y luego dejé el criterio. Viéndolo así, si considero que este criterio sobra, ya que una vez que sea usable (lo que es un requisito y no un criterio), luego reside ya en la dificultad del propio gestor y no en el lenguaje Go. Lo arreglo, muchas gracias!

2023-01-03 12:04 UTC, manujurado1 commented on docs/Gestor_Tareas.md
> +Tras hacer una búsqueda de las posibles opciones se han llegado a 2 posibles candidatos a ser el gestor de tareas del proyecto.
Los resultados que consideré los mejores fueron Make y Task, que son los que describo justo debajo de esta línea antes de elegir el que usaré para mi proyecto.

2023-01-03 12:07 UTC, JJ commented on docs/Gestor_Tareas.md
> +- Debido a facilidad de uso y complejidad de sintaxis, he elegido que Task será el gestor de tareas elegido para este proyecto.
No, es que no has puesto el freshness que tiene ni cómo lo has medido. Por otro lado, tendrás que hallar una forma comparable de medirlo que incluya a `make`

2023-01-03 12:17 UTC, manujurado1 commented on docs/Gestor_Tareas.md
> +- Debido a facilidad de uso y complejidad de sintaxis, he elegido que Task será el gestor de tareas elegido para este proyecto.
Vale, es verdad que no he plasmado ese criterio luego en las opciones, en la corrección haré mas énfasis en ese criterio. Gracias por el apunte!

2023-01-03 18:14 UTC, manujurado1 commented
Listo para revisión! @JJ 
Considero que he arreglado todos los fallos que tenía en el fichero que refleja la elección del gestor de tareas.
Muchas gracias!

2023-01-03 19:04 UTC, JJ approved these changes
Deberías haber puesto qué otras opciones has contemplado, pero por lo menos has sido coherente en la aplicación de los criterios.

2023-01-04 08:31 UTC, merged