Objetivo 4 [IV-22-23]
manujurado1/SportsBar-IV pull request #31
Opened 2023-01-05 11:57 UTC by manujurado1

* [x]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [x]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [x]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [x]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [x]  ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [x] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [x] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [x]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [x]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [x] ¿Se han testeado también las excepciones?

2023-01-09 18:12 UTC, manujurado1 commented
Listo para revisión! @JJ

2023-01-13 12:38 UTC, manujurado1 commented
Buenas @JJ, como tras 3 días ningún compañero ha revisado el PR y ya tengo el objetivo 5 listo para revisión le vuelvo a mencionar para que cuando pueda revise mi objetivo. Muchas gracias!

2023-01-13 16:28 UTC, JJ requested changes
Por favor, lee lo que has escrito, corrige y vuelve a enviarlo. Normalmente una cantidad de typos es inevitable, pero esto parece que haya sido escrito por una persona cuyo lenguaje nativo no es el español.

2023-01-13 16:28 UTC, JJ commented on README.md
> +- [Bilioteca asersiones y test runner](https://github.com/manujurado1/SportsBar-IV/blob/Objetivo-4/docs/Biblioteca_Asersiones_Y_Test_Runner.md)
typo

2023-01-13 16:28 UTC, JJ commented on docs/Biblioteca_Asersiones_Y_Test_Runner.md
> +# Biblioteca asersiones
typo

2023-01-13 16:28 UTC, JJ commented on docs/Biblioteca_Asersiones_Y_Test_Runner.md
> +- [BE](https://github.com/carlmjohnson/be?utm_campaign=awesomego&utm_medium=referral&utm_source=awesomego): Es una paquete minimalista de assersiones. A su favor es que es muy simple y fácil de usar,
¿una paquete?

2023-01-14 18:59 UTC, manujurado1 commented
@JJ Ya creo que está todo corregido, perdón por las molestias pero no sé donde tenía la cabeza ese día, sobre todo con la palabra aserciones. 😑

2023-01-16 07:30 UTC, JJ commented
> @JJ Ya creo que está todo corregido, perdón por las molestias pero no sé donde tenía la cabeza ese día, sobre todo con la palabra aserciones. expressionless

Me temo que esa no es la actitud adecuada para enfocar un milestone importante de un proyecto de ingeniería. Lo correcto es que borres esta rama y empieces desde cero, siguiendo la metodología que se ha explicado en clase. Entre otras cosas, el milestone tiene que estar asignado al PR desde el primer commit; si no se están haciendo los commits para llegar a un milestone, el enfoque es incorrecto.

Para asegurarnos que tienes la cabeza en el lugar adecuado, deberías firmar también todos y cada uno de los commits, que deben ser lo más atómicos posible, siguiendo las buenas prácticas habituales.

Tendrás que enviar de nuevo el PR y pasar los tests cuando esté todo correcto. Borro la entrada correspondiente en el fichero de la asignatura.

2023-01-16 12:23 UTC, closed without merging

2023-01-16 12:24 UTC, manujurado1 commented
Perfecto, creo otra rama para procurar hacer las cosas mejor. Muchas gracias!