[IV-22-23] Objetivo 1
manujurado1/SportsBar-IV pull request #5
Opened 2022-10-13 19:53 UTC by manujurado1

Sobre los milestones:
* [ x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [? ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente? -> He buscado que el milestone 0 sea el PMV más simple posible en la construcción del proyecto
* [x ] ¿Todos los milestones describen correctamente un producto, y no un
   concepto vago, una funcionalidad o una tarea?
* [ x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x ]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x ]  ¿El milestone 0 es mínimo *y* viable?
* [x ]  ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto? -> Quizás el último milestone se pueda dividir en varios, pero veo lógico que esos avances vayan juntos

Sobre las historias de usuario
* [x ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [x ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2022-10-14 08:29 UTC, PacoCP5 commented
Hola! He estado mirando tu objetivo 1 y voy a decirte lo que puedes mejorar:

- En tus milestones no debes añadir detalles de implementación y creo que los detalles de funcionalidad se incluyen en esto. En el primero creo que deberías limitarte solo a la representación del modelo e incluir todos los detalles de funcionalidad en la implementación de la lógica de negocio, es decir agruparía tus dos últimos milestone en uno solo que sea la implementación de la lógica de negocio.
- También, tus dos primeras personas creo que tienen un problema muy similar y creo que son el mismo tipo de usuario.
- Por último, la númeración de las Historias de Usuario empieza en 1, no en 0.

Revisa estas cosillas, sobre todo lo de los milestones y me dices para que lo vuelva a revisar. Animo! :smile:

2022-10-27 21:12 UTC, manujurado1 commented
Hola! Primero que todo muchas ganas por ayudarme a superar este objetivo. Siento haber tardado tanto tiempo en responderte, he tenido una racha que he tenido que dejar este objetivo un poco apartado, haré todo lo posible para que no pase más.

Respecto a tus mejoras, he cambiado los milestones ya que veo con mucho sentido lo que me comentaste. También cambié la numeración de las HU.

Por último, las personas las he mantenido por el momento ya que considero que el problema es bastante diferente respecto a que la segunda persona si necesita equipos por nivel, mientras que el uso del primero es mucho más simple.

Quizás no estuviera bien explicado y eso ha causado confusión, por lo que he intentado clarificar más el problema de cada persona.

¡Muchas gracias! @PacoCP5

2022-10-30 17:40 UTC, PacoCP5 approved these changes

2022-10-30 17:42 UTC, PacoCP5 commented
Hey @manujurado1!

Disculpa la tardanza en revisar tu proyecto. Acabo de ver tus nuevos cambios y lo veo todo bien. Creo que no se me escapa nada así que apruebo tus cambios y etiqueto a @JJ para que dé el visto bueno definitivo.

No olvides actualizar la lista del cuerpo del PR y marcar todas las comprobaciones (si eliminas el espacio de al lado de las x en "[x]" te aparecerá la casilla marcada) las cuales son todas afirmativas.

Mucho ánimo!

2022-10-31 13:16 UTC, manujurado1 commented
Cierto, voy a actualizar el cuerpo del PR.
Muchísimas gracias por la ayuda! @PacoCP5

2022-11-02 16:59 UTC, manujurado1 commented
Listo para revisión! @JJ

2022-11-02 17:54 UTC, JJ requested changes
Por favor, revisa los conceptos correspondientes a este objetivo, los errores frecuentes (en esta semana y las anteriores), y los [errores frecuentes de la semana 7](https://github.com/JJ/IV-22-23/blob/9c2b56f958f162051cfdaf4b67262f37c6560a58/sesiones/semana-07.md#objetivos), especialmente el primer punto del objetivo 2, el que empieza dicienco "Empezamos... "

2022-11-02 17:54 UTC, JJ commented on docs/Milestones.md
> +- [M0 - Creación del modelo de datos](https://github.com/manujurado1/SportsBar-IV/milestone/1)
¿Qué es exactamente un modelo de datos para ti?

2022-11-02 17:54 UTC, JJ commented on docs/User_stories.md
> +- [HU3 - Miguel quiere demostrar a sus amigos futboleros que él sigue sigue siendo el mejor.](https://github.com/manujurado1/SportsBar-IV/issues/4)
Y por supuesto, necesita a tu aplicación para hacerlo.

2022-11-02 18:23 UTC, manujurado1 commented on docs/Milestones.md
> +- [M0 - Creación del modelo de datos](https://github.com/manujurado1/SportsBar-IV/milestone/1)
Con el Milestone 0 planteo crear la base de datos del proyecto, dónde se diseñará y creará el Modelo de Grupo y de Jugador y la relación y dependencias entre ambos modelos.

2022-11-02 18:25 UTC, manujurado1 commented on docs/User_stories.md
> +- [HU3 - Miguel quiere demostrar a sus amigos futboleros que él sigue sigue siendo el mejor.](https://github.com/manujurado1/SportsBar-IV/issues/4)
Considero que para la HU3 la aplicación sería muy útil, ya que aparte de crear equipos igualados para sus sesiones de juego (al igual que para la HU2), pero con el plus de poder acceder al historia de partidos jugados y la puntuación interna que le otorga la aplicación, lo que enriquecería su competencia interna.

2022-11-02 18:27 UTC, JJ commented on docs/User_stories.md
> +- [HU3 - Miguel quiere demostrar a sus amigos futboleros que él sigue sigue siendo el mejor.](https://github.com/manujurado1/SportsBar-IV/issues/4)
Igualmente, repasa los conceptos de historia de usuario y los errores habituales, transcritos en las sesiones de las últimas semanas.

2022-11-02 18:35 UTC, manujurado1 commented
> Por favor, revisa los conceptos correspondientes a este objetivo, los errores frecuentes (en esta semana y las anteriores), y los [errores frecuentes de la semana 7](https://github.com/JJ/IV-22-23/blob/9c2b56f958f162051cfdaf4b67262f37c6560a58/sesiones/semana-07.md#objetivos), especialmente el primer punto del objetivo 2, el que empieza dicienco "Empezamos... "

Respecto a esto, tras haber revisado los errores frecuentes, entiendo que mis Milestones quizás el único fallo es haber creado solo 2 al generalizarlos demasiado.
Por otra parte creo que los 3 tipos de clientes son diferentes entre ellos, aunque tienen parte de problemática común, cada uno tiene sus singularidades y las HU se han escrito para ese tipo de clientes.

Por último, respecto al apartado de "hago esto porque se lo he visto a mi compañero", no sé si mi error ha sido cambiar mi propuesta de milestones bastantes tras la sugerencia de mi compañero, pero en ese caso vi muy razonable sus recomendaciones. Ya que en ningún momento he optado por la copia de contenido de compañeros con el fin de superar el objetivo.

Muchas gracias!

2022-11-02 19:26 UTC, manujurado1 commented
He corregido el M0, tras revisar que es lo que se espera de él.
De la misma forma, he corregido la HU3 ya que no expresaba el deseo/problema del usuario, lo que impedía ver para que le serviría la aplicación.

Listo para revisar @JJ 
Muchas gracias!

2022-11-02 19:51 UTC, JJ requested changes
Te rogaría que revisaras de nuevo lo que se requiere de los primeros milestones y que no cometas el mismo error que casualmetne han cometido varios compañeros/as y que ya he corregido. Lee los errores frecuentes, revisa el concepto de producto mínimamente viable, y trata de entender bien cómo se desarrolla un producto antes de aplicarlo a tu proyecto en particular para superar este objetivo.

2022-11-02 19:51 UTC, JJ commented on docs/Milestones.md
> +- [M0 -Implementación del modelo de datos](https://github.com/manujurado1/SportsBar-IV/milestone/1)
¿De qué datos vamos a implementar el modelo? ¿Cómo sabe la persona que lo haga de qué datos se trata?

2022-11-02 19:51 UTC, JJ commented on docs/Milestones.md
> +En este milestone se abordará la creación de un fichero ejecutable que genere los modelos de base de datos de "Grupo de juego" y "Jugador", con sus respectivos atributos, dependencias y limitaciones.
¿Lo primero que hay que hacer es un "modelo de bases de datos"? ¿Dónde hemos hablado de bases de datos en la asignatura? (O, para el caso, de modelos "de datos")

2022-11-09 20:54 UTC, manujurado1 commented
Tras revisar los errores y ver el vídeo sobre los PMV, considero que el objetivo está listo para revisión.
Muchas gracias! @JJ

2022-11-10 06:15 UTC, JJ approved these changes
Estaría correcto, pero por favor corrige las objeciones que se te han hecho lo antes posible

2022-11-10 06:15 UTC, JJ commented on docs/Milestones.md
> +Este milestone no se enfocará en implementación, sino en que el módulo compile correctamente.
¿Si no se implementa, cómo va a compilar correctamente?

2022-11-10 06:15 UTC, JJ commented on docs/User_stories.md
> +Javier quiere crear un grupo de juego con sus amigos de la infancia y obtener 2 equipos totalmente al azar una vez haya seleccionado quienes de sus amigos pueden asistir a esa sesión.
Los equipos al azar no ejercitan la lógica de negocio. Asegúrate de no ponerlo como un HU para el siguiente objetivo.

2022-11-10 09:06 UTC, merged