Objetivo 6 [IV-22-23]
manujurado1/SportsBar-IV pull request #69
Opened 2023-02-04 19:27 UTC by manujurado1

* [x] ¿Se ha evitado Circle CI, porque a estas alturas ya lo ha usado todo el
mundo?
* [x] ¿Se han establecido criterios *a priori* para elegir el sistema de
integración continua más conveniente y se han calificado los sistemas que
cumplan esos requisitos según esos criterios?
* [x] ¿Se han examinado varios sistemas de integración continua?
* [ ] ¿Se han configurado varios sistemas de integración continua?
* [ ] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [ ] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   del lenguaje con las que funciona correctamente nuestra aplicación?
* [ ] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?
* [ ] ¿Se han justificado correctamente las versiones del lenguaje que se están
testeando y se ha comprobado que no se comprueban varias veces lo mismo (la
misma versión en CI y en el contenedor Docker en otro sistema CI?

2023-02-05 18:42 UTC, manujurado1 commented
Listo para revisión! @JJ

2023-02-06 10:18 UTC, JJ requested changes
Repasa bien la lista de comprobación y el guión, por favor. A partir de la [semana 12 del año pasado](https://github.com/JJ/IV-22-23/blob/master/sesiones-21-22/semana-12.md) también hay errores frecuentes en este objetivo. Por favor, revísalos.

2023-02-06 10:18 UTC, JJ commented on docs/Sistema_CI.md
> +### Jenkins
Jenkins no es un sistema que puedas usar de forma gratuita.

2023-02-06 10:18 UTC, JJ commented on docs/Sistema_CI.md
> +- Hace falta descargar una aplicación
¿Y esto es algo que lo haga inservible para esta asignatura?

2023-02-06 10:18 UTC, JJ commented on docs/Sistema_CI.md
> +Entre las opciones plasmadas, se ha descartado Jenkins por la necesidad de tener que descargar la aplicación, CircleCi para evitar la opción más básica y SemaphoreCi debido a que no he llegado a sabe
Hay alguno más aparte de los mencionados. Si no quieres ponerlos todos, pon algún criterio de búsqueda que lo reduzca. Limitarte a los más populares no es lo que se busca aquí.

2023-02-06 10:18 UTC, JJ commented on .github/workflows/automatizar_unit_tests.yml
> +        run: go test -v ./...
Los task runners están para usarlos.

2023-02-06 10:18 UTC, JJ commented on .cirrus.yml
> +  image: manujurado1/sportsbar-iv:latest
¿Esta versión es diferente de la qu eusas en GitHub actions, o estás testeando en las dos lo mismo?

2023-02-06 10:22 UTC, manujurado1 commented on docs/Sistema_CI.md
> +### Jenkins
Vale, no lo tenía claro, lo rectifico

2023-02-06 10:22 UTC, manujurado1 commented on docs/Sistema_CI.md
> +- Hace falta descargar una aplicación
No lo hace inservible, pero me resultaba más cómodo el hecho de no tener que descargar nada, por eso lo añadí como criterio.

2023-02-06 10:24 UTC, manujurado1 commented on docs/Sistema_CI.md
> +Entre las opciones plasmadas, se ha descartado Jenkins por la necesidad de tener que descargar la aplicación, CircleCi para evitar la opción más básica y SemaphoreCi debido a que no he llegado a sabe
Vale, le echaré un vistazo a más posibles opciones y a la lista de criterios, aunque según he entendido, el hecho de que deba usar la API de checks de GitHub ya limita bastante la lista de opciones, ¿o estoy equivocado?

2023-02-06 10:24 UTC, manujurado1 commented on .github/workflows/automatizar_unit_tests.yml
> +        run: go test -v ./...
Cierto, lo cambié en cirrus pero en las actions se me olvidó.

2023-02-06 10:26 UTC, manujurado1 commented on .cirrus.yml
> +  image: manujurado1/sportsbar-iv:latest
Si, es diferente, está documentado en [este documento](https://github.com/manujurado1/SportsBar-IV/blob/Objetivo-6/docs/Versiones_Testeadas.md).

2023-02-06 10:29 UTC, manujurado1 commented
> Repasa bien la lista de comprobación y el guión, por favor. A partir de la [semana 12 del año pasado](https://github.com/JJ/IV-22-23/blob/master/sesiones-21-22/semana-12.md) también hay errores frecuentes en este objetivo. Por favor, revísalos.

Perfecto, le echaré un vistazo a los errores frecuentes del año pasado.

Sobre la lista de comprobación, ¿Qué opción he marcado que no esté haciendo correctamente? Ya que en principio veo que todos se cumplen y para poder enfocarme en el que no se esté cumpliendo realmente.

Muchas gracias por la corrección

2023-02-06 13:55 UTC, manujurado1 commented
Ya le he dado una vuelta a lo comentado.
Listo para revisión! @JJ

2023-02-11 11:47 UTC, merged