Mejorar estructura de datos. closes #85
manujurado1/SportsBar-IV pull request #90
Opened 2023-05-07 16:23 UTC by manujurado1

* [x] Mejorar estructura de datos
* [ ] Añadir historial a la estructura de datos
* [ ] Establecer criterios de modificación de nivel tras partido
* [ ] Crear funcionalidad insertar resultado -> Modificar niveles y guardar partido

2023-05-08 10:42 UTC, JJ commented
Recuerda referenciar siempre uno o varios issues *en el cuerpo del PR*, no en los commits.

2023-05-22 16:36 UTC, manujurado1 commented
Buenas @JJ . En principio este PR ya estaría listo, y a su vez toda la parte de la funcionalidad de la lógica de negocio de la aplicación.
Cuando puedas necesito una corrección para ver si necesito enfocar de distinta manera alguno de los apartados y plantear futuros pasos en el proyecto.
Gracias!

2023-05-22 17:10 UTC, JJ requested changes
Tendrías que intentar cubrir un poco mejor lo que quieres con los equipos equilibrados y, sobre todo, evitar todo tipo de números literales. Tienes que tratar de modelizar el problema de una forma un poco más formal. Un "nivel" es un estado, y los jugadores van a cambiar de estado, pero ¿cuantos estados necesitas? ¿Siempre van a ser dos equipos o puede haber 4 y estás buscando los equipos más nivelados con equipos que ya se han formado? En resumen, trata de avanzar mediante productos mínimamente viables modelizando el problema cada vez de forma más compleja.

2023-05-22 17:10 UTC, JJ commented on pkg/modelos/estadisticas_jugador.go
> +		this.Nivel = 100
Uf, qué poco me gusta esto. Si lo pones como producto mínimamente viable, vale, pero tienes que justificar que los niveles se trunquen por arriba y por abajo (y que haya tantos). El tema del nivel tienes que darle una pensada de forma que no sea tan puesto ahí a martillazos y sobre todo que no tenga tantos números mágicos.
En todo caso, no se deben usar valores literales, defínelos siempre como una constante. Y haz bien el truncado;  fíjate que por encima de 100 reseteas a 100, pero sin embargo por debajo de 0 reseteas a 1.

2023-05-22 17:10 UTC, JJ commented on pkg/modelos/grupo.go
> +func (this *Grupo) ModificarNiveles(Partido DatosPartido) (bool, error) {
Cuando veas funciones tan complejas, con tantos if, tienes siempre que reexaminar las suposiciones que te han llevado a ella. Una vez más, como PMV puede servir, pero son difíciles de testear y complejas de entender.

2023-05-22 17:10 UTC, JJ commented on pkg/modelos/grupo.go
> +				estadisticas := this.Jugadores[jugador]
DRY, don't repeat yourself. Es el mismo código que abajo, con diferentes datos.

2023-05-22 17:10 UTC, JJ commented on pkg/modelos/grupo.go
> +		if ((Partido.ResultadoEquipo1 - 3) >= Partido.ResultadoEquipo2) && (Partido.ResultadoEquipo1 >= (Partido.ResultadoEquipo2 * 2)) {
Tantas constantes ad hoc pueden servir como PMV, pero en general no son muy aceptables. Más, una vez, no uses literales, usa constantes y si puede ser, variables.

2023-05-22 17:10 UTC, JJ commented on pkg/modelos/grupo.go
> +				estadisticas.setNivel(int(this.Jugadores[jugador].Nivel + 5))
Uf código repetido, demasiados literales...

2023-05-22 17:36 UTC, manujurado1 commented
> Tendrías que intentar cubrir un poco mejor lo que quieres con los equipos equilibrados y, sobre todo, evitar todo tipo de números literales. Tienes que tratar de modelizar el problema de una forma un poco más formal. Un "nivel" es un estado, y los jugadores van a cambiar de estado, pero ¿cuantos estados necesitas? ¿Siempre van a ser dos equipos o puede haber 4 y estás buscando los equipos más nivelados con equipos que ya se han formado? En resumen, trata de avanzar mediante productos mínimamente viables modelizando el problema cada vez de forma más compleja.

Gracias por la corrección. El problema de evitar los literales lo entiendo, me pongo a corregirlo para evitarlos.

Luego, respecto al tema de los niveles he seguido el issue #64 y respecto a los equipos igualados, todo está enfocado a 2 equipos, siguiendo la definición de igualados de #66.

Pero si aún así, si tengo que replantearlo o hacerlo de alguna manera diferente házmelo saber para entenderlo mejor.

Por último, creo que es buena opción replantear el sistema de modificación de niveles añadiendo uno que funciones siendo mucho más simple para enfocarlo como PMV .

2023-05-22 17:37 UTC, manujurado1 commented on pkg/modelos/estadisticas_jugador.go
> +		this.Nivel = 100
La justificación de esta forma de tratar y truncar los niveles es debido a #64, pero digo lo mismo que en la respuesta general, si no es la forma correcta pues agradecería una ayuda de la dirección en la que plantearlo.

2023-05-23 18:29 UTC, manujurado1 commented
Buenas @JJ, le he dado una vuelta a lo comentado ayer, cuando puedas echarle un vistazo me comentas a ver si aunque sea el enfoque es algo más correcto. 
Muchas gracias!

2023-05-24 06:12 UTC, JJ requested changes
Primero, temas generales
1. No puedes avanzar a un milestone hasta que no hayas completado el anterior. En este caso, dado que estás implementando la lógica de negocio, estarías en el milestone 1; pero ese está ya "cerrado" 
2. Debes intentar implementar buenas prácticas; si no las conoces, debes intentar usar algún tipo de herramienta automática que te las indique. Un *linter* es imprescindible en casi todos los casos, pero en algunos casos necesitarás un analizador de *code smells*, que te diga si hay alguna bandera roja en tu código tal como alta complejidad ciclomática, funciones demasiado largas, literales en el código, y demás.
3. No debes implementar nada sin que haya un issue que exprese un problema.

2023-05-24 06:12 UTC, JJ commented on pkg/modelos/grupo.go
>  		NombreGrupo = "Grupo"
En estas cosas tienes que seguir también historias de usuario, que planteen por ejemplo que todos los nombres tienen que ser diferentes.
Adicionalmente, tratándose de una inicialización de un valor basado en un argumento, debería estar al principio.

2023-05-24 06:12 UTC, JJ commented on pkg/modelos/grupo.go
> +			return success, error
De la misma forma, debería ser un error específico.

2023-05-24 06:12 UTC, JJ commented on pkg/modelos/grupo.go
> +	_, existe := this.Jugadores[NombreJugador]
Un proyecto debe tratar de hacerse en etapas sucesivas, con complejidad creciente, avanzando en productos mínimamente viables. La disponibilidad de un jugador no me parece que sea parte de un producto mínimamente viable. Lo que se crea de esta forma son PRs excesivamente complejos, 4 ficheros, con una gran cantidad de cambios, que requieren mucho esfuerzo por parte de quien los hace y quien los corrige.

2023-05-24 06:12 UTC, JJ commented on pkg/modelos/grupo.go
> +				NivelTotalEquipoB += this.Jugadores[Jugador].Nivel
Una vez más, complicación excesiva. Hay un concepto que es la *complejidad ciclomática* que, cuando alcanza un nivel excesivo en una función, indica una solución posiblemente equivocada o un nivel de abstracción inadecuado. En este caso diría que es el problema. Tienes una cantidad de comprobaciones e if excesivas, por no mencionar que estás trabajando con disponibilidad que no creo que sea parte de un producto mínimamente viable.

2023-05-24 06:12 UTC, JJ commented on pkg/modelos/grupo.go
> +	if err != nil {
Estas "burbujeando" un error inespecífico a un nivel superior. La gestión de errores es esencial en un programa, y los issues deben de decir claramente qué se hace con ellos.

2023-05-24 06:12 UTC, JJ commented on pkg/modelos/grupo_test.go
> +func TestConsultarHistorial(t *testing.T) {
Los tests prueban comportamientos, no simples funciones como la consulta.

2023-05-24 06:12 UTC, JJ commented on pkg/modelos/grupo_test.go
> +func TestModificarNiveles(t *testing.T) {
Sigues usando números mágicos. Los tests, una vez más, deben comprobar comportamientos y deben parecerse lo más posible a las historias de usuario o problemas de menor nivel que resuelvan.

2023-06-05 08:13 UTC, closed without merging